web/web10/web09/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'web09.views.home', name='home'),
    # url(r'^web09/', include('web09.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/$', 'blog.views.index'),
    url(r'^nav/(\d+)/', 'blog.views.disp_nav'),
)

web/web10/blog/models.py
from django.db import models


class Nav(models.Model):
    name = models.CharField(max_length=10)

    def __unicode__(self):
        return self.name

class New(models.Model):
    title = models.CharField(max_length=50)
    p_date = models.DateTimeField()
    content = models.TextField()
    img = models.FileField(upload_to='newimg/')
    nav = models.ForeignKey(Nav)

    def __unicode__(self):
        return self.title[0:10]

web/web10/blog/views.py
from blog.models import Nav
from django.shortcuts import render_to_response

def index(req):
    nav_list = Nav.objects.all()
    return render_to_response('index.html', {'nav_list':nav_list})


def disp_nav(req,nav_id):
    nav_list = Nav.objects.all()
    nav = Nav.objects.get(id__exact=nav_id)
    return render_to_response('nav.html', {'nav':nav,'nav_list':nav_list})

web/web10/blog/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{%block title%}test page{%endblock%}</title>
        <style type="text/css">
        #main{
            width: 900px;
            margin: 0 auto;
        }
        #header{
            height: 100px;
            background-color: red;
        }
        #header li{
            display: inline-block;
            width: 60px;
        }

        #left{
            width: 300px;
            float:left;
        }

        #right{
            width: 550px;
            float: right;
        }
       #footer{
            border: 1px solid black;
            height: 80px;
            clear: both;
            background-color: blue;
        }
        </style>
        <script type="text/javascript">
        </script>
    </head>
    <div id="main">
        <div id="header">
        {%block header%}
        <ul>
            {%for nav in nav_list%}
            <li><a href="/nav/{{nav.id}}/">{{nav.name}}</a> </li>
            {%endfor%}
        </ul>
        {%endblock%}
        </div>
        <div id="content">
            <div id="left">
            {%block left%}left
            {%endblock%}
            </div>
            <div id="right">
            {%block right%}right
            {%endblock%}
            </div>
        </div>
        <div id="footer">
            {%block footer%}footer
            {%endblock%}
        </div>
    </div>
    <body>
    </body>
</html>

web/web10/blog/templates/header.html
<div>
<ul>
{%for nav in nav_list%}
<li><a href="/nav/{{nav.id}}/">{{nav}}</a></li>
{%endfor%}
</ul>
</div>

web/web10/blog/templates/index.html
{%extends "base.html"%}

{%block title%}首页-我们的...
{%endblock%}

{%block right%}
    首页内容
{%endblock%}

web/web10/blog/templates/nav.html
{%extends "base.html"%}

{%block title%}{{nav.name}}
{%endblock%}

{%block right%}
    <ul>
    {%for new in nav.new_set.all %}
    <li><a href>{{new.title}}</a></li>
    {%endfor%}
    </ul>
{%endblock%}
<h1>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</h1>